#spring.application.name=onepage
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB

# URL base del servicio externo (en Docker = nombre del contenedor)
feign:
  client:
    base-url: ${FEIGN_CLIENT_BASE_URL}