services:

  # ============================================
  # BACKEND - Spring Boot (Java 21)
  # ============================================
  # Se conecta a db-battilana (MySQL existente en network-battilana)
  backend:
    build:
      context: ./backend-onepage
      dockerfile: Dockerfile
    container_name: onepage-backend
    env_file: .env
    ports:
      - "8085:8080"
    networks:
      - network-battilana

  # ============================================
  # FRONTEND - Angular + Nginx
  # ============================================
  frontend:
    build:
      context: ./frontend-onepage
      dockerfile: Dockerfile
    container_name: onepage-frontend
    ports:
      - "4201:80"
    depends_on:
      - backend
    networks:
      - network-battilana

# ============================================
# RED EXTERNA - Usa la red ya existente
# ============================================
networks:
  network-battilana:
    external: true
